from pathlib import Path
path = Path("src/com/dabomstew/pkrandom/pokemon/editors/Gen5MovesSheetPanel.java")
text = path.read_text()
text = text.replace("                case COL_MIN_HITS:\n                        move.minHits = clampInt(parseInt(val), 0, 15);\n                        if (move.maxHits < move.minHits) {\n                            move.maxHits = move.minHits;\n                        }\n                        break;", "                case COL_MIN_HITS:\n                        move.minHits = clampInt(parseInt(val), 0, 15);\n                        if (move.maxHits < move.minHits) {\n                            move.maxHits = move.minHits;\n                        }\n                        updateHitCount(move);\n                        break;")
text = text.replace("                case COL_MAX_HITS:\n                        move.maxHits = clampInt(parseInt(val), 0, 15);\n                        if (move.maxHits < move.minHits) {\n                            move.minHits = move.maxHits;\n                        }\n                        break;", "                case COL_MAX_HITS:\n                        move.maxHits = clampInt(parseInt(val), 0, 15);\n                        if (move.maxHits < move.minHits) {\n                            move.minHits = move.maxHits;\n                        }\n                        updateHitCount(move);\n                        break;")
text = text.replace("                case COL_MIN_TRAP_TURNS:\n                        move.minTrapTurns = clampInt(parseInt(val), 0, 255);\n                        break;", "                case COL_MIN_TRAP_TURNS:\n                        move.minTrapTurns = clampInt(parseInt(val), 0, 255);\n                        if (move.minTrapTurns == 0 && move.maxTrapTurns == 0 && !move.isTrapMove) {\n                            // allow clearing via Trap Move column\n                        } else {\n                            move.isTrapMove = move.isTrapMove || move.minTrapTurns > 0 || move.maxTrapTurns > 0;\n                        }\n                        break;")
text = text.replace("                case COL_MAX_TRAP_TURNS:\n                        move.maxTrapTurns = clampInt(parseInt(val), 0, 255);\n                        break;", "                case COL_MAX_TRAP_TURNS:\n                        move.maxTrapTurns = clampInt(parseInt(val), 0, 255);\n                        if (move.minTrapTurns == 0 && move.maxTrapTurns == 0 && !move.isTrapMove) {\n                            // allow clearing via Trap Move column\n                        } else {\n                            move.isTrapMove = move.isTrapMove || move.minTrapTurns > 0 || move.maxTrapTurns > 0;\n                        }\n                        break;")
text = text.replace("                        move.statusPercentChance = clampInt(parseInt(val), 0, 255);\n                        break;", "                        move.statusPercentChance = clampInt(parseInt(val), 0, 255);\n                        move.secondaryEffectChance = (int) move.statusPercentChance;\n                        break;")
path.write_text(text)
